### PR TITLE
Emacs Configuration Guide

### PR DESCRIPTION
**Pull request by chauhan739**
## Description

Added detailed information about how to make Emacs useful for C++ development.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🇺🇸 Translation  
- [x] 🗑️ Chore

### CODE REVIEW

**Comment by B4mbus** [comment]
Hey. Thank you for your collaboration. The article is great, tho I'd suggest moving the `completely optional` emacs configuration section to the very bottom and merging it with `customizing emacs theme`, what do you think? The main purpose of the article is to show the user how to customize the editor for C++ development, after all. After that I'd be ready to merge.

**Comment by chauhan739** [comment]
Yeah, I think that would be great. All the optional items will be grouped together then. But I am unable to do that right now because I am afk for few days.

**Comment by chauhan739** [comment]
Never mind, I did the required changes.

**Comment by B4mbus** [comment]
Very nice. Thank you!

**Pull request merged**
